Repository edenia/eden-spend-explorer, pull requests merged in 2022-09, with the labels that each got.

#79 refactor(hasura): change column name
  hapi/src/gql/eden-election.gql.js
  hapi/src/gql/eden-historic-election.gql.js
  hapi/src/services/eden-delegates.service.js
  hapi/src/services/eden-historic-delegates.service.js
  hasura/migrations/default/1662157545683_alter_table_public_eden_historic_election_alter_column_election_round/down.sql
  hasura/migrations/default/1662157545683_alter_table_public_eden_historic_election_alter_column_election_round/up.sql
  hasura/migrations/default/1662157566016_alter_table_public_eden_election_alter_column_election_round/down.sql
  hasura/migrations/default/1662157566016_alter_table_public_eden_election_alter_column_election_round/up.sql
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/IncomeReport/index.js
Labels: bug, backend

#78 feat(webapp): improve UI from main page
  .github/workflows/push-prod-environment.yaml
  webapp/public/images/EOS-Spend-Explorer.png
  webapp/public/images/eoscostarica-logo.png
  webapp/public/images/user@3x.png
  webapp/public/index.html
  webapp/src/components/Footer/index.js
  webapp/src/components/Footer/styles.js
  webapp/src/components/Header/index.js
  webapp/src/components/Header/styles.js
  webapp/src/components/Sidebar/index.js
  webapp/src/components/Sidebar/styles.js
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/layouts/Dashboard/index.js
  webapp/src/layouts/Dashboard/styles.js
  webapp/src/routes/IncomeReport/IncomeChart.js
  webapp/src/routes/IncomeReport/IncomeSelect.js
  webapp/src/routes/IncomeReport/IncomeTable.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/index.js
  webapp/src/theme/palette.js
Labels: frontend

#87 feat(hapi): add category on income transaction
  hapi/src/services/eden-historic-delegates.service.js
  hapi/src/services/hyperion/updaters/genesiseden-withdraw.updater.js
  hasura/migrations/default/1662398157336_alter_table_public_eden_transaction_alter_column_txid/down.sql
  hasura/migrations/default/1662398157336_alter_table_public_eden_transaction_alter_column_txid/up.sql
Labels: backend

#91 feat(webapp): show in income view the next disbursement
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/IncomeReport/index.js
Labels: frontend

#92 feat(webapp): add 18 colors for delegates chart
  webapp/src/constants/income.constants.js
  webapp/src/constants/index.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
Labels: frontend

#93 feat(webapp): thousands separator
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/IncomeReport/IncomeTable.js
  webapp/src/routes/IncomeReport/index.js
Labels: frontend

#95 fix(github): changes variables to correct api
  .github/workflows/push-dev-environment.yaml
  .github/workflows/push-prod-environment.yaml
Labels: bug

#105 feat(webapp): hide delegate field #90
  webapp/src/routes/IncomeReport/IncomeSelect.js
Labels: frontend

#110 Feat/exchange rate graph 81
  .env.example
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/IncomeReport/IncomeChart.js
Labels: frontend

#111 feat(webapp): load chart data by default
  hasura/metadata/databases/default/tables/public_total_income_by_election.yaml
  hasura/metadata/databases/default/tables/tables.yaml
  hasura/migrations/default/1663083837350_run_sql_migration/down.sql
  hasura/migrations/default/1663083837350_run_sql_migration/up.sql
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/IncomeReport/IncomeChart.js
  webapp/src/routes/IncomeReport/IncomeSelect.js
  webapp/src/routes/IncomeReport/IncomeTable.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
Labels: frontend

#113 fix(hasura): add permissions to guest role
  hasura/metadata/databases/default/tables/public_total_income_by_election.yaml
Labels: bug

#136 fix(webapp): incomes graphs works fine #131
  hasura/metadata/databases/default/tables/public_historic_incomes.yaml
  hasura/metadata/databases/default/tables/public_incomes_claimed_or_unclaimed.yaml
  hasura/metadata/databases/default/tables/tables.yaml
  hasura/migrations/default/1664213346535_run_sql_migration/down.sql
  hasura/migrations/default/1664213346535_run_sql_migration/up.sql
  hasura/migrations/default/1664228084282_run_sql_migration/down.sql
  hasura/migrations/default/1664228084282_run_sql_migration/up.sql
  hasura/migrations/default/1664228175080_drop_view_public_incomes_claimed_or_unclaimed/down.sql
  hasura/migrations/default/1664228175080_drop_view_public_incomes_claimed_or_unclaimed/up.sql
  hasura/migrations/default/1664228203908_run_sql_migration/down.sql
  hasura/migrations/default/1664228203908_run_sql_migration/up.sql
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/IncomeReport/IncomeChart.js
  webapp/src/routes/IncomeReport/IncomePieChart.js
Labels: bug, frontend

#132 feat(webapp): add withdrawal date to table
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/IncomeReport/IncomeChart.js
  webapp/src/routes/IncomeReport/IncomeTable.js
Labels: frontend

#135 feat(webapp): option to select all election years and last election
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/IncomeReport/IncomeSelect.js
Labels: frontend

#141 fix(webapp): deleted wrong migrations
  hasura/migrations/default/1663721329888_run_sql_migration/down.sql
  hasura/migrations/default/1663721329888_run_sql_migration/up.sql
  hasura/migrations/default/1663777506562_run_sql_migration/down.sql
  hasura/migrations/default/1663777506562_run_sql_migration/up.sql
  hasura/migrations/default/1663777521430_run_sql_migration/down.sql
  hasura/migrations/default/1663777521430_run_sql_migration/up.sql
  hasura/migrations/default/1664228084282_run_sql_migration/down.sql
  hasura/migrations/default/1664228084282_run_sql_migration/up.sql
  hasura/migrations/default/1664228175080_drop_view_public_incomes_claimed_or_unclaimed/down.sql
  hasura/migrations/default/1664228175080_drop_view_public_incomes_claimed_or_unclaimed/up.sql
Labels: bug
