Repository edenia/eden-spend-explorer, pull requests merged in 2022-08, with the labels that each got.

#45 chore(hapi):Adapt for election and delegates information #44
  hapi/src/gql/eden-delegates.gql.js
  hapi/src/gql/eden-election.gql.js
  hapi/src/gql/eden-transaction.gql.js
  hapi/src/gql/index.js
  hapi/src/services/eden-delegates.service.js
  hapi/src/services/eden-election.service.js
  hapi/src/services/hyperion/updaters/eosiotoken-transfer.updater.js
  hapi/src/services/worker.service.js
Labels: backend

#59 fix(hapi): Requested changes fixed #58j
  hapi/src/constants/index.js
  hapi/src/constants/transaction.constant.js
  hapi/src/utils/updater.util.js
Labels: bug

#60 feat(hapi): Saves and categorizes all transfers #56
  hapi/src/constants/transaction.constant.js
  hapi/src/services/hyperion/updaters/eosiotoken-transfer.updater.js
  hapi/src/utils/updater.util.js
Labels: backend

#62 fix(hapi):Error in main fixed #61
  hapi/src/constants/transaction.constant.js
  hapi/src/services/hyperion/updaters/eosiotoken-transfer.updater.js
Labels: bug

#63 feat(webapp): add table and graph for income
  .env.example
  .github/workflows/push-dev-environment.yaml
  .github/workflows/push-prod-environment.yaml
  docker-compose.yaml
  webapp/Dockerfile
  webapp/makefile
  webapp/package.json
  webapp/src/components/Sidebar/index.js
  webapp/src/config/main.config.js
  webapp/src/gql/income.gql.js
  webapp/src/gql/index.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/IncomeReport/IncomeChart.js
  webapp/src/routes/IncomeReport/IncomeSelect.js
  webapp/src/routes/IncomeReport/IncomeTable.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/index.js
  webapp/src/theme/typography.js
  webapp/yarn.lock
  yarn.lock
Labels: frontend

#65 fix(webapp): delete duplicated useEffect
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/IncomeReport/IncomeSelect.js
Labels: frontend
