Repository edenia/eden-spend-explorer, pull requests merged in 2022-11, with the labels that each got.

#209 feat(webapp): improve about view
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/About/index.js
  webapp/src/routes/About/styles.js
Labels: frontend

#207 feat(webapp): improve homepage
  webapp/public/index.html
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/Home/index.js
  webapp/src/routes/Home/styles.js
Labels: frontend

#206 feat(webapp): UI for smart contract integration
  webapp/public/icons/add_circle.svg
  webapp/public/icons/arrow_icon.svg
  webapp/public/icons/close.svg
  webapp/public/icons/edit_tool.svg
  webapp/src/components/Snackbar/index.js
  webapp/src/components/TableReport/index.js
  webapp/src/constants/income.constants.js
  webapp/src/gql/index.js
  webapp/src/gql/spendTools.gql.js
  webapp/src/hooks/customHooks/useForm.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/SpendTools/index.js
  webapp/src/routes/SpendTools/styles.js
  webapp/src/routes/index.js
  webapp/src/theme/palette.js
  webapp/src/theme/typography.js
  webapp/src/utils/format-with-thousand-separator.js
Labels: frontend

#213 Feat/Update views
  hasura/migrations/default/1667419709572_run_sql_migration/down.sql
  hasura/migrations/default/1667419709572_run_sql_migration/up.sql
  webapp/src/App.js
  webapp/src/components/BarChartGeneralReport/index.js
  webapp/src/components/BarChartGeneralReport/styles.js
  webapp/src/components/Header/index.js
  webapp/src/components/LineAreaChartReport/index.js
  webapp/src/components/PieChartReport/index.js
  webapp/src/components/PieChartReport/styles.js
  webapp/src/components/StackedChartReport/index.js
  webapp/src/components/StackedChartReport/styles.js
  webapp/src/components/TableReport/index.js
  webapp/src/constants/income.constants.js
  webapp/src/gql/delegate.gql.js
  webapp/src/gql/expense.gql.js
  webapp/src/gql/general.gql.js
  webapp/src/gql/income.gql.js
  webapp/src/gql/index.js
  webapp/src/hooks/customHooks/useDelegateReportState.js
  webapp/src/hooks/customHooks/useExpenseReportState.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/DelegateReport/index.js
  webapp/src/routes/DelegateReport/styles.js
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/ExpenseReportDelegates/index.js
  webapp/src/routes/Home/index.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/IncomeReportDelegates/index.js
  webapp/src/routes/IncomeReportGeneral/styles.js
  webapp/src/routes/index.js
  webapp/src/utils/new-format-objects.js
Labels: frontend

#216 feat(webapp): change to correct titles
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/DelegateReport/index.js
  webapp/src/routes/DelegateReport/styles.js
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/Home/index.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
Labels: bug

#227 feat(webapp): update piechart view
  webapp/src/components/PieChartReport/index.js
  webapp/src/components/PieChartReport/styles.js
  webapp/src/hooks/customHooks/useExpenseReportState.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/hooks/customHooks/useTresuryBalanceState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/utils/new-format-objects.js
Labels: bug, frontend

#225 feat(backend): save income data
  hapi/package.json
  hapi/src/services/dfuse/index.js
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-withdraw.updater.js
  hapi/src/services/eden-historic-delegates.service.js
  hapi/src/services/eden-unclaimed-funds.service.js
  hapi/yarn.lock
Labels: backend

#230 fix(webapp): information table
  webapp/src/components/TableReport/index.js
Labels: bug, frontend

#231 fix(webapp): trasury loading
  webapp/src/components/TreasuryBalance/index.js
  webapp/src/hooks/customHooks/useTresuryBalanceState.js
  webapp/src/utils/index.js
  webapp/src/utils/sleep.js
Labels: bug, frontend

#229 feat(backend): listen categorize action in backend
  hapi/src/gql/eden-transaction.gql.js
  hapi/src/services/dfuse/index.js
  hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
  hapi/src/services/dfuse/updaters/index.js
Labels: backend

#233 fix(webapp): title for category and delegate are backwards
  webapp/src/routes/ExpenseReport/index.js
Labels: bug, frontend

#236 fix(webapp): bug fixed
  webapp/src/gql/income.gql.js
Labels: bug

#237 feat(webapp): modify the memo transaction in frontend
  webapp/src/gql/expense.gql.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
Labels: frontend

#239 feat(webapp): update list transaction information
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/routes/SpendTools/styles.js
Labels: frontend

#241 content(webapp): redundant data in table
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/utils/new-format-objects.js
Labels: frontend

#246 Feat/delegate view 228
  docker-compose.yaml
  hasura/metadata/databases/default/tables/public_expenses_by_category_and_delegate.yaml
  hasura/metadata/databases/default/tables/tables.yaml
  hasura/migrations/default/1668203188320_run_sql_migration/down.sql
  hasura/migrations/default/1668203188320_run_sql_migration/up.sql
  hasura/migrations/default/1668203357463_run_sql_migration/down.sql
  hasura/migrations/default/1668203357463_run_sql_migration/up.sql
  hasura/migrations/default/1668203391516_rename_view_public_categorized_expenses_by_delegate/down.sql
  hasura/migrations/default/1668203391516_rename_view_public_categorized_expenses_by_delegate/up.sql
  hasura/migrations/default/1668203557310_drop_view_public_categorized_expenses/down.sql
  hasura/migrations/default/1668203557310_drop_view_public_categorized_expenses/up.sql
  webapp/public/icons/chiefdelegate-icon.png
  webapp/public/icons/delegate-icon.svg
  webapp/public/icons/lv1-icon.png
  webapp/public/icons/lv2-icon.png
  webapp/public/icons/lv3-icon.png
  webapp/src/components/Accordion/index.js
  webapp/src/components/Accordion/styles.js
  webapp/src/components/BarChartReport/index.js
  webapp/src/components/BarChartReport/styles.js
  webapp/src/components/DelegateDetails/index.js
  webapp/src/components/DelegateDetails/styles.js
  webapp/src/components/PieChartReport/index.js
  webapp/src/components/Select/index.js
  webapp/src/components/Sidebar/index.js
  webapp/src/components/StackedBarChartReport/index.js
  webapp/src/components/StackedBarChartReport/styles.js
  webapp/src/components/TreasuryBalance/styles.js
  webapp/src/gql/delegate.gql.js
  webapp/src/gql/eden_member.gql.js
  webapp/src/hooks/customHooks/useDelegateReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/DelegateReport/index.js
  webapp/src/routes/DelegateReport/styles.js
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/index.js
  webapp/src/utils/eden-members.js
  webapp/src/utils/index.js
  webapp/src/utils/new-format-objects.js
Labels: frontend

#245 feat(webapp): check texts and json
  webapp/src/components/BarChartReport/index.js
  webapp/src/components/BarChartReport/styles.js
  webapp/src/components/PieChartReport/index.js
  webapp/src/components/PieChartReport/styles.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/Home/index.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/SpendTools/index.js
Labels: frontend

#254 feat(webapp): not display data in loading treasury
  webapp/src/components/TreasuryBalance/index.js
Labels: frontend

#252 style(webapp): styles refactor
  webapp/src/components/BarChartReport/index.js
  webapp/src/components/BarChartReport/styles.js
  webapp/src/components/DelegateDetails/index.js
  webapp/src/components/DelegateDetails/styles.js
  webapp/src/components/PieChartReport/index.js
  webapp/src/components/PieChartReport/styles.js
  webapp/src/components/Select/index.js
  webapp/src/components/StackedBarChartReport/index.js
  webapp/src/components/StackedBarChartReport/styles.js
  webapp/src/routes/DelegateReport/index.js
  webapp/src/routes/DelegateReport/styles.js
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/SpendTools/styles.js
  webapp/src/theme/palette.js
Labels: frontend

#258 fix(webapp): loading scroll
  webapp/src/layouts/Dashboard/index.js
Labels: bug, frontend

#263 fix(webapp): correct percent
  hapi/src/services/dfuse/index.js
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-withdraw.updater.js
  hasura/migrations/default/1669315874247_run_sql_migration/down.sql
  hasura/migrations/default/1669315874247_run_sql_migration/up.sql
  hasura/migrations/default/1669316455331_run_sql_migration/down.sql
  hasura/migrations/default/1669316455331_run_sql_migration/up.sql
Labels: frontend

#264 fix(webapp): add substract to uncategorized
  webapp/src/utils/new-format-objects.js
Labels: bug, frontend

#267 fix(webapp): correct Capital Letters
  webapp/src/components/PieChartReport/index.js
  webapp/src/language/en.json
  webapp/src/language/es.json
Labels: frontend

#262 Improve delegate view
  hapi/src/constants/frontend.constant.js
  hapi/src/constants/index.js
  hapi/src/gql/delegate-frontend.gql.js
  hapi/src/gql/index.js
  hapi/src/routes/get-delegates.route.js
  hapi/src/routes/index.js
  hapi/src/services/delegate-frontend.service.js
  hapi/src/services/index.js
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  webapp/src/components/Accordion/index.js
  webapp/src/components/Accordion/styles.js
  webapp/src/components/DelegateDetails/index.js
  webapp/src/components/DelegateDetails/styles.js
  webapp/src/gql/delegate.gql.js
  webapp/src/hooks/customHooks/useDelegateReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/DelegateReport/index.js
  webapp/src/utils/index.js
  webapp/src/utils/new-format-objects.js
  webapp/src/utils/useImperativeQuery.js
Labels: bug, frontend

#269 fix(hasura): add permisions guest
  hasura/metadata/actions.yaml
Labels: bug

#271 fix(webapp): A param was missing in the function
  webapp/src/components/Accordion/index.js
Labels: bug

#273 style(webapp): improve mobile view
  webapp/src/components/Accordion/index.js
  webapp/src/components/Accordion/styles.js
  webapp/src/components/BarChartReport/index.js
  webapp/src/components/BarChartReport/styles.js
  webapp/src/components/Select/index.js
  webapp/src/components/Select/styles.js
  webapp/src/components/StackedBarChartReport/styles.js
  webapp/src/components/TableReport/index.js
  webapp/src/components/TableReport/styles.js
  webapp/src/routes/DelegateReport/index.js
  webapp/src/routes/DelegateReport/styles.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/Home/styles.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/SpendTools/styles.js
Labels: frontend

#280 refactor(webapp, hapi): make queries of frontend from backend
  hapi/src/gql/income-frontend.gql.js
  hapi/src/gql/index.js
  hapi/src/routes/get-income.route.js
  hapi/src/routes/index.js
  hapi/src/services/income-frontend.service.js
  hapi/src/services/index.js
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/utils/new-format-objects.js
Labels: backend, frontend

#281 feat(webapp): use EOSDetective instead of EOSAuthority
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/IncomeReport/index.js
Labels: frontend
