Repository edenia/eden-spend-explorer, pull requests merged in 2022-10, with the labels that each got.

#143 feat(webapp): add percent un/claimed to table
  hasura/metadata/databases/default/tables/public_percent_by_all_elections.yaml
  hasura/metadata/databases/default/tables/public_percent_by_delegades.yaml
  hasura/metadata/databases/default/tables/public_percent_by_delegates.yaml
  hasura/metadata/databases/default/tables/tables.yaml
  hasura/migrations/default/1664322664765_run_sql_migration/down.sql
  hasura/migrations/default/1664322664765_run_sql_migration/up.sql
  hasura/migrations/default/1664324349407_run_sql_migration/down.sql
  hasura/migrations/default/1664324349407_run_sql_migration/up.sql
  hasura/migrations/default/1664324578106_rename_view_public_percent_by_delegades/down.sql
  hasura/migrations/default/1664324578106_rename_view_public_percent_by_delegades/up.sql
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/IncomeReport/IncomeTable.js
  webapp/src/routes/IncomeReport/index.js
Labels: frontend

#153 feat(webapp): download graphics
  webapp/package.json
  webapp/src/routes/IncomeReport/IncomeChart.js
  webapp/src/routes/IncomeReport/IncomePieChart.js
  webapp/src/routes/IncomeReport/IncomeStackedChart.js
  webapp/yarn.lock
Labels: frontend

#150 refactor(readme): changes incorrect links
  README.md
  webapp/src/components/Footer/index.js
Labels: bug

#149 fix(hapi): use dfuse instead of hyperion
  .env.example
  .github/workflows/push-dev-environment.yaml
  .github/workflows/push-prod-environment.yaml
  docker-compose.yaml
  hapi/package.json
  hapi/src/config/dfuse.config.js
  hapi/src/config/hyperion.config.js
  hapi/src/config/index.js
  hapi/src/constants/transaction.constant.js
  hapi/src/gql/dfuse-state.gql.js
  hapi/src/gql/index.js
  hapi/src/services/dfuse/index.js
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-withdraw.updater.js
  hapi/src/services/dfuse/updaters/index.js
  hapi/src/services/eden-historic-delegates.service.js
  hapi/src/services/eden-unclaimed-funds.service.js
  hapi/src/services/hyperion/index.js
  hapi/src/services/hyperion/updaters/genesiseden-fundtransfer.updater.js
  hapi/src/services/worker.service.js
  hapi/src/utils/dfuse.util.js
  hapi/src/utils/index.js
  hapi/yarn.lock
  hasura/metadata/databases/default/tables/public_dfuse_state.yaml
  hasura/metadata/databases/default/tables/tables.yaml
  hasura/migrations/default/1664520952659_rename_table_public_hyperion_state/down.sql
  hasura/migrations/default/1664520952659_rename_table_public_hyperion_state/up.sql
  hasura/migrations/default/1664521138915_alter_table_public_dfuse_state_drop_column_last_synced_at/down.sql
  hasura/migrations/default/1664521138915_alter_table_public_dfuse_state_drop_column_last_synced_at/up.sql
  hasura/migrations/default/1664521211661_alter_table_public_dfuse_state_add_column_last_synced_at/down.sql
  hasura/migrations/default/1664521211661_alter_table_public_dfuse_state_add_column_last_synced_at/up.sql
  kubernetes/configmaps.yaml
Labels: backend

#151 feat(webapp): sort funtionality for tables
  webapp/package.json
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/IncomeReport/IncomeChart.js
  webapp/src/routes/IncomeReport/IncomeTable.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/yarn.lock
Labels: frontend

#156 fix(webapp): fix table error
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/IncomeReport/IncomeTable.js
  webapp/src/routes/IncomeReport/index.js
Labels: bug, frontend

#157 Feat/create views and query to expenses graphs 154
  hasura/metadata/databases/default/tables/public_historic_expenses.yaml
  hasura/metadata/databases/default/tables/public_percent_by_all_elections_expenses.yaml
  hasura/metadata/databases/default/tables/public_percent_by_all_elections_incomes.yaml
  hasura/metadata/databases/default/tables/public_percent_by_delegates_expenses.yaml
  hasura/metadata/databases/default/tables/public_percent_by_delegates_incomes.yaml
  hasura/metadata/databases/default/tables/public_total_by_category.yaml
  hasura/metadata/databases/default/tables/public_total_by_category_and_election.yaml
  hasura/metadata/databases/default/tables/public_total_by_election.yaml
  hasura/metadata/databases/default/tables/public_transaction_by_category_and_election.yaml
  hasura/metadata/databases/default/tables/tables.yaml
  hasura/migrations/default/1664992048496_rename_view_public_total_claimed_and_unclaimed/down.sql
  hasura/migrations/default/1664992048496_rename_view_public_total_claimed_and_unclaimed/up.sql
  hasura/migrations/default/1664992226596_run_sql_migration/down.sql
  hasura/migrations/default/1664992226596_run_sql_migration/up.sql
  hasura/migrations/default/1664992236977_run_sql_migration/down.sql
  hasura/migrations/default/1664992236977_run_sql_migration/up.sql
  hasura/migrations/default/1664999115898_rename_view_public_total_claimed_and_unclaimed_by_election/down.sql
  hasura/migrations/default/1664999115898_rename_view_public_total_claimed_and_unclaimed_by_election/up.sql
  hasura/migrations/default/1664999286321_run_sql_migration/down.sql
  hasura/migrations/default/1664999286321_run_sql_migration/up.sql
  hasura/migrations/default/1664999291690_run_sql_migration/down.sql
  hasura/migrations/default/1664999291690_run_sql_migration/up.sql
  hasura/migrations/default/1665003604382_rename_view_public_total_income_by_election/down.sql
  hasura/migrations/default/1665003604382_rename_view_public_total_income_by_election/up.sql
  hasura/migrations/default/1665003693998_run_sql_migration/down.sql
  hasura/migrations/default/1665003693998_run_sql_migration/up.sql
  hasura/migrations/default/1665008343278_rename_view_public_incomes_claimed_and_unclaimed/down.sql
  hasura/migrations/default/1665008343278_rename_view_public_incomes_claimed_and_unclaimed/up.sql
  hasura/migrations/default/1665008724098_run_sql_migration/down.sql
  hasura/migrations/default/1665008724098_run_sql_migration/up.sql
  hasura/migrations/default/1665010371612_run_sql_migration/down.sql
  hasura/migrations/default/1665010371612_run_sql_migration/up.sql
  hasura/migrations/default/1665011247469_rename_view_public_percent_by_all_elections/down.sql
  hasura/migrations/default/1665011247469_rename_view_public_percent_by_all_elections/up.sql
  hasura/migrations/default/1665011285410_rename_view_public_percent_by_delegates/down.sql
  hasura/migrations/default/1665011285410_rename_view_public_percent_by_delegates/up.sql
  hasura/migrations/default/1665013773947_run_sql_migration/down.sql
  hasura/migrations/default/1665013773947_run_sql_migration/up.sql
  hasura/migrations/default/1665086507794_run_sql_migration/down.sql
  hasura/migrations/default/1665086507794_run_sql_migration/up.sql
  hasura/migrations/default/1665086943523_run_sql_migration/down.sql
  hasura/migrations/default/1665086943523_run_sql_migration/up.sql
  hasura/migrations/default/1665087253238_run_sql_migration/down.sql
  hasura/migrations/default/1665087253238_run_sql_migration/up.sql
  hasura/migrations/default/1665089874222_run_sql_migration/down.sql
  hasura/migrations/default/1665089874222_run_sql_migration/up.sql
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/IncomeReport/index.js
Labels: backend

#159 fix(hasura): add permissions to guest rol
  hasura/metadata/databases/default/tables/public_historic_expenses.yaml
  hasura/metadata/databases/default/tables/public_percent_by_all_elections_expenses.yaml
  hasura/metadata/databases/default/tables/public_percent_by_delegates_expenses.yaml
  hasura/metadata/databases/default/tables/public_percent_by_delegates_incomes.yaml
  hasura/metadata/databases/default/tables/public_total_by_category.yaml
  hasura/metadata/databases/default/tables/public_total_by_category_and_election.yaml
  hasura/metadata/databases/default/tables/public_total_by_election.yaml
  hasura/metadata/databases/default/tables/public_transaction_by_category_and_election.yaml
Labels: bug

#162 Fix/duplicate data on views 160
  hasura/migrations/default/1665175945840_run_sql_migration/down.sql
  hasura/migrations/default/1665175945840_run_sql_migration/up.sql
  hasura/migrations/default/1665176042800_run_sql_migration/down.sql
  hasura/migrations/default/1665176042800_run_sql_migration/up.sql
Labels: bug

#167 refactor(hapi) save all memo
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
Labels: backend

#169 Fix/validate if exists a new election 168
  hapi/src/services/eden-historic-delegates.service.js
Labels: bug, backend

#182 fix(hapi): improve dfuse data saving time
  hapi/src/gql/eden-delegates.gql.js
  hapi/src/services/dfuse/index.js
  hapi/src/services/eden-historic-delegates.service.js
  hapi/src/utils/updater.util.js
  hasura/metadata/databases/default/tables/public_eden_delegates.yaml
  hasura/migrations/default/1666133326081_alter_table_public_eden_delegates_add_column_last_synced_at/down.sql
  hasura/migrations/default/1666133326081_alter_table_public_eden_delegates_add_column_last_synced_at/up.sql
  hasura/migrations/default/1666164783646_alter_table_public_eden_historic_election_alter_column_election/down.sql
  hasura/migrations/default/1666164783646_alter_table_public_eden_historic_election_alter_column_election/up.sql
  hasura/migrations/default/1666203318207_run_sql_migration/down.sql
  hasura/migrations/default/1666203318207_run_sql_migration/up.sql
  webapp/src/gql/expense.gql.js
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useExpenseReportState.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
Labels: backend

#185 fix(hapi): add validation by name transaction
  hapi/src/services/dfuse/index.js
Labels: backend

#195 fix(webapp): general and delegate views
  hasura/metadata/databases/default/tables/public_expenses_by_delegate.yaml
  hasura/metadata/databases/default/tables/public_incomes_by_delegate.yaml
  hasura/metadata/databases/default/tables/tables.yaml
  hasura/migrations/default/1666812605922_run_sql_migration/down.sql
  hasura/migrations/default/1666812605922_run_sql_migration/up.sql
  hasura/migrations/default/1666821581396_run_sql_migration/down.sql
  hasura/migrations/default/1666821581396_run_sql_migration/up.sql
  webapp/src/components/LineAreaChartReport/index.js
  webapp/src/components/StackedChartReport/index.js
  webapp/src/gql/expense.gql.js
  webapp/src/gql/income.gql.js
  webapp/src/hooks/customHooks/useExpenseReportState.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/ExpenseReportDelegates/index.js
  webapp/src/routes/ExpenseReportGeneral/index.js
  webapp/src/routes/IncomeReportDelegates/index.js
  webapp/src/routes/IncomeReportGeneral/index.js
  webapp/src/utils/new-format-objects.js
Labels: frontend

#201 fix(hasura): add guest role permiss
  hasura/metadata/databases/default/tables/public_expenses_by_delegate.yaml
  hasura/metadata/databases/default/tables/public_incomes_by_delegate.yaml
Labels: bug

#204 fix(env): change api endpoint
  .env.example
Labels: backend
