Repository edenia/eden-spend-explorer, pull requests merged in 2022-12, with the labels that each got.

#289 Refactor/pagespeed insights 277
  webapp/package.json
  webapp/src/components/Footer/index.js
  webapp/src/components/Header/index.js
  webapp/src/components/LanguageSelector/index.js
  webapp/yarn.lock
Labels: backend, frontend

#291 refactor(hasura): unused queries and tables deleted
  hapi/src/gql/dfuse-state.gql.js
  hapi/src/gql/index.js
  hasura/metadata/databases/default/tables/tables.yaml
  hasura/migrations/default/1670356199172_drop_table_public_dfuse_state/down.sql
  hasura/migrations/default/1670356199172_drop_table_public_dfuse_state/up.sql
Labels: backend

#294 docs(readme): update logo, wireframes and certain text
  README.md
  docs/images/example-eden-tx.png
  docs/images/logo_eden.png
  docs/images/logo_edeneos.png
  docs/images/wireframes.png
Labels: documentation

#305 feat(webapp): get balance from blockchain
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/routes/SpendTools/index.js
Labels: bug

#304 feat(webapp): change min width
  webapp/src/components/TreasuryBalance/styles.js
Labels: bug

#312 fix(hapi): memo migration
  hapi/yarn.lock
  hasura/metadata/databases/default/tables/public_eden_transaction.yaml
  hasura/migrations/default/1670610149638_alter_table_public_eden_transaction_add_column_memo/down.sql
  hasura/migrations/default/1670610149638_alter_table_public_eden_transaction_add_column_memo/up.sql
Labels: bug, backend

#310 feat(webapp, hapi): add election date to bar chart
  hapi/src/gql/income-frontend.gql.js
  hapi/src/services/income-frontend.service.js
  webapp/src/components/BarChartReport/index.js
  webapp/src/gql/expense.gql.js
  webapp/src/hooks/customHooks/useExpenseReportState.js
  webapp/src/utils/new-format-objects.js
Labels: backend, frontend

#313 fix(webapp): change size and padding icon
  webapp/src/components/LanguageSelector/index.js
  webapp/src/components/LanguageSelector/styles.js
Labels: UI / UX Design, frontend

#315 fix(webapp): delegate chart expenses
  webapp/src/components/Select/index.js
  webapp/src/components/Sidebar/index.js
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/utils/new-format-objects.js
Labels: bug

#316 fix(webapp): changes margin sidebar
  webapp/src/components/Sidebar/styles.js
  webapp/src/layouts/Dashboard/styles.js
Labels: UI / UX Design, frontend

#317 feat(webapp): add report a bug
  webapp/src/constants/footer.js
Labels: enhancement, frontend

#324 fix(webapp): improving user experience
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
  hasura/metadata/databases/default/tables/public_eden_transaction.yaml
  webapp/src/components/TableReport/index.js
  webapp/src/components/TreasuryBalance/index.js
  webapp/src/gql/expense.gql.js
  webapp/src/gql/general.gql.js
  webapp/src/gql/spendTools.gql.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/hooks/customHooks/useTresuryBalanceState.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/SpendTools/index.js
  webapp/src/routes/SpendTools/styles.js
Labels: frontend

#323 Fix/add i18 to footer 318
  webapp/src/components/Footer/index.js
  webapp/src/constants/footer.js
  webapp/src/constants/index.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/SpendTools/index.js
Labels: bug, frontend

#328 fix(webapp): review margin between sidebar and main content
  webapp/src/layouts/Dashboard/index.js
Labels: frontend

#327 feat(webapp): add interactions to the main logo
  webapp/package.json
  webapp/src/components/Sidebar/index.js
  webapp/src/components/Sidebar/styles.js
  webapp/yarn.lock
Labels: frontend

#334 fix(webapp): add ual api to yaml file
  .github/workflows/push-dev-environment.yaml
  .github/workflows/push-prod-environment.yaml
Labels: bug, frontend

#332 Feat/create a help section 292
  webapp/public/icons/about-icon.svg
  webapp/public/icons/help-icon.svg
  webapp/public/icons/home-icon.svg
  webapp/public/images/balance-EN.webp
  webapp/public/images/balance-ES.webp
  webapp/public/images/charts-EN.webp
  webapp/public/images/charts-ES.webp
  webapp/public/images/role-access-EN.webp
  webapp/public/images/role-access-ES.webp
  webapp/public/images/spend-tools-ES.webp
  webapp/public/images/spend-tools2-ES.webp
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/Help/index.js
  webapp/src/routes/Help/styles.js
  webapp/src/routes/index.js
Labels: enhancement, UI / UX Design, frontend

#349 fix(hapi): dfuse on dev error
  hapi/src/services/dfuse/index.js
  hapi/src/services/eden-delegates.service.js
  hapi/src/services/eden-historic-delegates.service.js
  makefile
  webapp/src/hooks/customHooks/useDelegateReportState.js
Labels: bug

#337 feat(webapp): add translation to download button
  webapp/src/components/BarChartReport/index.js
  webapp/src/components/PieChartReport/index.js
  webapp/src/language/en.json
  webapp/src/language/es.json
Labels: enhancement, frontend

#341 fix(webapp): add missing images
  webapp/public/images/spend-tools-EN.webp
  webapp/public/images/spend-tools2-EN.webp
  webapp/src/language/es.json
  webapp/src/routes/Help/index.js
Labels: enhancement, frontend

#345 feat(webapp): implement new homepage design
  webapp/public/images/home1.png
  webapp/public/images/home2.png
  webapp/public/images/home3.png
  webapp/public/images/home4.png
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/Home/index.js
  webapp/src/routes/Home/styles.js
Labels: frontend

#352 fix(webapp): add enviroment variable
  .env.example
  .github/workflows/push-dev-environment.yaml
  .github/workflows/push-prod-environment.yaml
  docker-compose.yaml
  webapp/Dockerfile
  webapp/makefile
  webapp/src/components/Sidebar/index.js
  webapp/src/config/main.config.js
  webapp/src/hooks/customHooks/useDelegateReportState.js
Labels: bug, frontend

#354 fix(webapp): verify if is delegate
  hapi/src/services/dfuse/index.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/utils/new-format-objects.js
Labels: bug

#358 fix(hapi): fix new format elections income
  hapi/src/services/income-frontend.service.js
Labels: bug

#360 Fix/remove year from drop down selector 356
  webapp/src/hooks/customHooks/useExpenseReportState.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/IncomeReport/index.js
Labels: bug

#361 Fix/create an access validation only for delegates 359
  webapp/src/App.js
  webapp/src/gql/general.gql.js
Labels: bug

#366 fix(webapp): show uncategorized in delegate view by piechart
  webapp/src/hooks/customHooks/useDelegateReportState.js
  webapp/src/utils/new-format-objects.js
Labels: bug, frontend

#363 fix(hapi): fix save fundtransfer in real time
  hapi/src/services/dfuse/index.js
  hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
  hapi/src/utils/updater.util.js
Labels: bug, backend

#372 fix(webapp) fix stakedBar data
  webapp/src/utils/new-format-objects.js
Labels: bug, frontend

#367 fix(webapp): changes data format on expense
  webapp/src/utils/new-format-objects.js
Labels: bug
