Repository edenia/eden-spend-explorer, pull requests merged in 2023-01, with the labels that each got.

#375 feat(webapp): save the most recent idElection spend tool view
  hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
  hapi/src/utils/updater.util.js
  webapp/src/App.js
  webapp/src/gql/general.gql.js
  webapp/src/gql/spendTools.gql.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/hooks/customHooks/useTresuryBalanceState.js
  webapp/src/routes/SpendTools/index.js
  webapp/src/utils/new-format-objects.js
Labels: frontend

#377 feat(webapp): add export buttom
  webapp/src/components/TableReport/index.js
Labels: enhancement, frontend

#379 refactor(webapp): delete unused code
  webapp/src/gql/general.gql.js
  webapp/src/hooks/customHooks/useDelegateReportState.js
  webapp/src/hooks/customHooks/useExpenseReportState.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/IncomeReport/index.js
Labels: enhancement

#384 fix(webapp):bad images dimentions on mobile version in help section
  webapp/src/routes/Help/index.js
  webapp/src/routes/Help/styles.js
Labels: bug, frontend

#388 fix(webapp): add order to request query
  webapp/src/gql/eden-expense.gql.js
Labels: bug, frontend

#392 fix(webapp): show data by date and add filter
  webapp/src/components/LineChartReport/index.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/utils/new-format-objects.js
Labels: bug, enhancement, UI / UX Design

#398 Production Release
  webapp/src/components/LineChartReport/index.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/utils/new-format-objects.js
Labels: WIP

#403 fix(webapp): add missing validation
  webapp/src/hooks/customHooks/useSpendToolsState.js
Labels: bug, frontend

#402 fix(webapp): make requested changes on line chart
  .github/workflows/push-prod-environment.yaml
  webapp/src/components/BarChartReport/index.js
  webapp/src/components/BarChartReport/styles.js
  webapp/src/components/LineChartReport/index.js
  webapp/src/components/LineChartReport/styles.js
  webapp/src/components/PieChartReport/styles.js
  webapp/src/components/TableReport/styles.js
  webapp/src/routes/DelegateReport/styles.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/IncomeReport/styles.js
Labels: enhancement, frontend

#394 feat(webapp): display current distribution rate
  webapp/src/gql/eden-election.gql.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/IncomeReport/treasury-disbursements-info.js
Labels: frontend

#405 feat(webapp): add prefill memo to description
  webapp/src/routes/SpendTools/index.js
Labels: enhancement, frontend

#406 fix(webapp): check the number Txs
  contract/edenexplorer/include/edenexplorer.hpp
  contract/edenexplorer/src/edenexplorer.cpp
  contract/edenexplorer/tests/tests.cpp
  hapi/src/gql/eden-transaction.gql.js
  hapi/src/services/dfuse/index.js
  hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
  hapi/src/utils/dfuse.util.js
  hasura/metadata/databases/default/tables/public_eden_transaction.yaml
  hasura/migrations/default/1673556739883_alter_table_public_eden_transaction_add_column_digest/down.sql
  hasura/migrations/default/1673556739883_alter_table_public_eden_transaction_add_column_digest/up.sql
  hasura/migrations/default/1673565665020_alter_table_public_eden_transaction_drop_column_memo/down.sql
  hasura/migrations/default/1673565665020_alter_table_public_eden_transaction_drop_column_memo/up.sql
  webapp/src/gql/eden-expense.gql.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/SpendTools/index.js
  webapp/src/routes/SpendTools/spendTool-table-report.js
  webapp/src/routes/SpendTools/styles.js
Labels: backend, frontend

#404 fix(webapp): negative expense
  webapp/src/components/TableReport/index.js
  webapp/src/components/TableReport/styles.js
  webapp/src/hooks/customHooks/useDelegateReportState.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/SpendTools/styles.js
  webapp/src/utils/new-format-objects.js
Labels: bug, frontend

#408 fix(webapp): add missing variable
  webapp/src/routes/SpendTools/index.js
Labels: bug

#410 fix(webapp): fix recategorize error
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/routes/SpendTools/index.js
Labels: bug

#416 feat(webapp): translate next distribution text
  webapp/src/language/es.json
Labels: enhancement, frontend

#412 Production Release
  .github/workflows/push-dev-environment.yaml
  .github/workflows/push-prod-environment.yaml
  contract/edenexplorer/include/edenexplorer.hpp
  contract/edenexplorer/src/edenexplorer.cpp
  contract/edenexplorer/tests/tests.cpp
  hapi/src/gql/eden-transaction.gql.js
  hapi/src/services/dfuse/index.js
  hapi/src/services/dfuse/updaters/edenexplorer-categorize.updater.js
  hapi/src/services/dfuse/updaters/eosiotoken-transfer.updater.js
  hapi/src/services/dfuse/updaters/genesiseden-fundtransfer.updater.js
  hapi/src/utils/dfuse.util.js
  hasura/metadata/databases/default/tables/public_eden_transaction.yaml
  hasura/migrations/default/1673556739883_alter_table_public_eden_transaction_add_column_digest/down.sql
  hasura/migrations/default/1673556739883_alter_table_public_eden_transaction_add_column_digest/up.sql
  hasura/migrations/default/1673565665020_alter_table_public_eden_transaction_drop_column_memo/down.sql
  hasura/migrations/default/1673565665020_alter_table_public_eden_transaction_drop_column_memo/up.sql
  webapp/src/components/BarChartReport/index.js
  webapp/src/components/BarChartReport/styles.js
  webapp/src/components/LineChartReport/index.js
  webapp/src/components/LineChartReport/styles.js
  webapp/src/components/PieChartReport/styles.js
  webapp/src/components/TableReport/index.js
  webapp/src/components/TableReport/styles.js
  webapp/src/gql/eden-election.gql.js
  webapp/src/gql/eden-expense.gql.js
  webapp/src/hooks/customHooks/useDelegateReportState.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/routes/DelegateReport/styles.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/IncomeReport/treasury-disbursements-info.js
  webapp/src/routes/SpendTools/index.js
  webapp/src/routes/SpendTools/spendTool-table-report.js
  webapp/src/routes/SpendTools/styles.js
  webapp/src/utils/new-format-objects.js
Labels: WIP

#418 feat(webapp): add estimated treasury to the lineChart
  webapp/src/components/LineChartReport/index.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/hooks/customHooks/useTresuryBalanceState.js
  webapp/src/language/en.json
  webapp/src/language/es.json
  webapp/src/utils/new-format-objects.js
Labels: enhancement, frontend

#421 perf(webapp): organize components inside gh
  webapp/src/components/Accordion/styles.js
  webapp/src/components/BarChartReport/custom-barChart.js
  webapp/src/components/BarChartReport/custom-tooltip-barChart.js
  webapp/src/components/BarChartReport/index.js
  webapp/src/components/BarChartReport/styles.js
  webapp/src/components/DelegateDetails/styles.js
  webapp/src/components/LineChartReport/custom-lineChart.js
  webapp/src/components/LineChartReport/custom-tooltip-lineChart.js
  webapp/src/components/LineChartReport/index.js
  webapp/src/components/LineChartReport/styles.js
  webapp/src/components/PieChartReport/custom-pieChart.js
  webapp/src/components/PieChartReport/index.js
  webapp/src/components/PieChartReport/styles.js
  webapp/src/components/RadioFilter/index.js
  webapp/src/components/StackedBarChartReport/custom-stackedBarChart.js
  webapp/src/components/StackedBarChartReport/custom-tooltip-stackedBarChart.js
  webapp/src/components/StackedBarChartReport/index.js
  webapp/src/components/StackedBarChartReport/styles.js
  webapp/src/components/TableReport/styles.js
  webapp/src/gql/eden-expense.gql.js
  webapp/src/gql/eden-income.gql.js
  webapp/src/hooks/customHooks/useSpendToolsState.js
  webapp/src/language/en.json
  webapp/src/routes/DelegateReport/delegate-accordion.js
  webapp/src/routes/DelegateReport/delegate-details.js
  webapp/src/routes/DelegateReport/index.js
  webapp/src/routes/DelegateReport/styles.js
  webapp/src/routes/ExpenseReport/expense-table-report.js
  webapp/src/routes/ExpenseReport/index.js
  webapp/src/routes/ExpenseReport/styles.js
  webapp/src/routes/IncomeReport/income-table-report.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/routes/IncomeReport/styles.js
  webapp/src/routes/IncomeReport/treasury-disbursements-info.js
  webapp/src/routes/SpendTools/index.js
  webapp/src/routes/SpendTools/spendTool-form-report.js
  webapp/src/routes/SpendTools/spendTool-modal-report.js
  webapp/src/routes/SpendTools/styles.js
Labels: enhancement, frontend

#423 fix(webapp): improve ui ux treasury balance chart
  webapp/src/components/LineChartReport/custom-lineChart.js
  webapp/src/components/LineChartReport/index.js
  webapp/src/components/LineChartReport/styles.js
  webapp/src/components/Sidebar/index.js
  webapp/src/hooks/customHooks/useIncomeReportState.js
  webapp/src/routes/Home/styles.js
  webapp/src/routes/IncomeReport/index.js
  webapp/src/utils/new-format-objects.js
Labels: WIP, enhancement, frontend

#426 fix(webapp): ui ux improvements on treasury chart
  webapp/src/components/BarChartReport/custom-barChart.js
  webapp/src/components/LineChartReport/custom-lineChart.js
  webapp/src/components/LineChartReport/index.js
  webapp/src/components/LineChartReport/styles.js
  webapp/src/language/en.json
  webapp/src/language/es.json
Labels: enhancement, frontend

#430 feat(webapp): add loading to piechart when is empty
  webapp/public/images/treasury-chart-EN.webp
  webapp/public/images/treasury-chart-ES.webp
  webapp/src/components/BarChartReport/custom-barChart.js
  webapp/src/components/LineChartReport/custom-lineChart.js
  webapp/src/components/LineChartReport/styles.js
  webapp/src/components/PieChartReport/custom-pieChart.js
Labels: enhancement, frontend
